---
documentclass: report
fontsize: 11pt # Options Include 10pt, 11pt, or 12pt
header-includes:
- \usepackage{crimson}
- \usepackage[T1]{fontenc}
- \usepackage[margin=1in]{geometry}
- \renewcommand{\baselinestretch}{1}
- \usepackage{enumitem}
output:
  pdf_document:
    number_sections: no # Yes if you wanted numbered sections
  word_document: default
urlcolor: blue
---


\text{\bfseries\LARGE{ESM 228 Practicum 2}}
\newline
\text{\Large{Simone Albuquerque, Sara Orofino, Elena Zhang}}
\newline
\text{\Large{May 4, 2020}}
\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}



## Theory of Change  
Organization:  
Program Title:  

## Measure Definition

Define the eight most important measures for the Theory of Change.  
\newline
**Measure 1**  

*Measurement goal* :    
*Exact measure to be taken* :    
*Unit of measurement* :    
*Source of data* :    
*Rationale for choice of measure* :    
*Responsibility for data collection* :      
*Frequency of data collection* :    

**Measure 2**  

*Measurement goal* :    
*Exact measure to be taken* :    
*Unit of measurement* :    
*Source of data* :    
*Rationale for choice of measure* :    
*Responsibility for data collection* :      
*Frequency of data collection* :   

**Measure 3**  

*Measurement goal* :    
*Exact measure to be taken* :    
*Unit of measurement* :    
*Source of data* :    
*Rationale for choice of measure* :    
*Responsibility for data collection* :      
*Frequency of data collection* :   

**Measure 4**  

*Measurement goal* :    
*Exact measure to be taken* :    
*Unit of measurement* :    
*Source of data* :    
*Rationale for choice of measure* :    
*Responsibility for data collection* :      
*Frequency of data collection* :    

**Measure 5**  

*Measurement goal* :    
*Exact measure to be taken* :    
*Unit of measurement* :    
*Source of data* :    
*Rationale for choice of measure* :    
*Responsibility for data collection* :      
*Frequency of data collection* :   

**Measure 6**  

*Measurement goal* :    
*Exact measure to be taken* :    
*Unit of measurement* :    
*Source of data* :    
*Rationale for choice of measure* :    
*Responsibility for data collection* :      
*Frequency of data collection* :   
  
**Measure 7**  

*Measurement goal* :    
*Exact measure to be taken* :    
*Unit of measurement* :    
*Source of data* :    
*Rationale for choice of measure* :    
*Responsibility for data collection* :      
*Frequency of data collection* :   

**Measure 8**  

*Measurement goal* :    
*Exact measure to be taken* :    
*Unit of measurement* :    
*Source of data* :    
*Rationale for choice of measure* :    
*Responsibility for data collection* :      
*Frequency of data collection* :   
  
## Sampling Strategy
