---
title: "measurement_html"
author: "Sara Orofino"
date: "4/28/2020"
output: html_document
---

## Theory of Change  
Organization:  American Rivers  
Program Title: American Rivers Fuel Reduction Program  

[Insert image of TOC here]  

## Measure Definition

**Measure 1**  

*Measurement goal* :    
*Exact measure to be taken* :    
*Unit of measurement* :    
*Source of data* :    
*Rationale for choice of measure* :    
*Responsibility for data collection* :      
*Frequency of data collection* :  


## Sampling Strategy

**Measure 1 **  
*Target population*: Private land owners in the Sierra Nevada watershed  
*Challenges to representative sampling*: Cal Fire permits are only required for private land owner burns, any fuel reduction or prescribed burns on federal land uses a different process and much of the land in the Sierra Nevada watershed is federally owned.  
*Sampling procedure* -  need a way to match the participants to their permit application

outcome variable is binary -0/1 did or did not submit an application
random draws from binary distribution with some probability
how many people on average in the population would submit a permit?
  - maybe data from years prior could inform this and this would give the probability
  
similar in structure to Mark's example of if the technology was better or worse for fish